import type { GetServerSidePropsContext, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import About from '../components/home'
import Icons from '../components/Icons'
import { items } from '../data'
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='' style={{marginLeft: "-1.5rem", marginRight: "-1.5rem"}}>
       <About />
      </main>
      </div>
  )
}

export default Home
