import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import ProjectsComp from '../components/ProjectsComp'
// import styles from '../styles/Home.module.css'

const Projects: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProjectsComp />
      </main>
      </div>
  )
}

export default Projects
