import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Bar from '../components/Bar'
import { languages, tools } from '../data'
// import styles from '../styles/Home.module.css'

const Resume: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>My Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='px-6 py-2'>
        <section className='grid gap-6 md:grid-cols-2'>
          <div>
            <h5 className='my-3 text-2xl font-bold'>Education</h5>
            <div>
              <h5 className='font-semibold'> Rivers State ICT</h5>
              <p className='font-semibold'>Codegaminator (2018)</p>
              <p className='my-3 italic'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque quod quo suscipit, pariatur voluptatem recusandae quis </p>
            </div>
            <div>
              <h5 className='font-semibold'>Google Africa Developer Scholarship</h5>
              <p className='font-semibold'>(2019)</p>
              <p className='my-3 italic'>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
              </p>
            </div>
            <div>
              <h5 className='font-semibold'>Microsoft Africa Azure Training </h5>
              <p className='font-semibold'>(2020)</p>
              <p className='my-3 italic'>Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
            </div>
          </div>
          <div>
            <h5 className='my-3 text-2xl font-bold'>Experience</h5>
            <div>
              <h5 className='font-semibold'> HNG 7 Internship</h5>
              <p className='font-semibold'>Frontend Developer (2019-2020)</p>
              <p className='my-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque quod quo suscipit, </p>
            </div>
            <div>
              <h5 className='font-semibold'>Frontend Engineer Jnr.</h5>
              <p className='font-semibold'>Tech Creek (2020)</p>
              <p className='my-3'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloremque quod quo suscipit, pariatur voluptatem recusandae.</p>
            </div>
          </div>
        </section>
        <section className='grid gap-6 md:grid-cols-2'>
          <div>
            <h5 className='my-3 text-2xl font-bold'>
              Languages & Frameworks
            </h5>
            <div>
              {
                languages.map(language => <Bar data={language} key={language.name} />)
              }
            </div>
          </div>
          <div>
            <h5 className='my-3 text-2xl font-bold'>
              Tools & Softwares
            </h5>
            <div>
              {
                tools.map(tool => <Bar data={tool} key={tool.name} />)
              }
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

export default Resume
